title: Bellwright Data
description:
  Bellwright database and reference with quests, items, NPCs, rewards, recipes,
  resources, crafting, locations, and other game data.
markdown: kramdown
plugins:
  - jekyll-sitemap
