title: Bellwright Wiki & Guide
description: >
  Bellwright wiki and database with quests, items, NPCs, rewards, recipes,
  resources, crafting, locations, guides, and other game data.
markdown: kramdown
plugins:
  - jekyll-sitemap
